name: takaful
version: 1.2.0+6
publish_to: none
description: The Takaful Official Application.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1
  flutter_flavor: ^3.1.3
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  flutter_form_builder: ^9.1.1
  lottie: ^2.7.0
  awesome_select: ^6.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  firebase_messaging: ^14.7.6
  flutter_udid: ^2.0.1
  package_info: ^2.0.2
  skeletons: ^0.0.3
  connectivity_plus: ^5.0.2
  flutter_widget_from_html_core: ^0.14.9
  firebase_core: ^2.24.0
  animated_splash_screen: ^1.3.0
  flutter_easyloading: ^3.0.5
  form_builder_validators: ^9.1.0
  salomon_bottom_bar: ^3.3.2
  keyboard_actions: ^4.2.0
  form_builder_image_picker: ^4.0.0
  carousel_slider: 4.2.1
  auto_size_text: 3.0.0
  form_builder_phone_field: ^2.0.1
  country_picker: ^2.0.23
  device_info_plus: ^9.1.1
  pdf_render: ^1.4.5
  share_plus: ^7.2.1
  hexcolor: 3.0.1
  intl: ^0.18.1
  flutter_inappwebview: ^5.8.0
  back_button_interceptor: ^7.0.0
  easy_image_viewer: 1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: 0.9.1

dependency_overrides:
  intl: 0.18.0

flutter:
  assets:
    - lib/assets/animations/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/pdf/
  uses-material-design: true

flutter_launcher_name:
  name: Takaful Cambodia

flutter_icons:
  android: launcher_icon
  image_path: lib/assets/images/logo.jpeg
  ios: true
  remove_alpha_ios: true
