name: takaful
version: 1.2.0+6
publish_to: none
description: The Takaful Official Application.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1
  flutter_flavor: ^3.1.4
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  flutter_form_builder: ^10.0.0
  lottie: ^3.3.1
  awesome_select: ^6.0.0
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  firebase_messaging: ^15.2.6
  flutter_udid: ^4.0.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.3
  firebase_core: ^3.12.1
  animated_splash_screen: ^1.3.0
  flutter_easyloading: ^3.0.5
  form_builder_validators: ^11.1.2
  salomon_bottom_bar: ^3.3.2
  keyboard_actions: ^4.2.0
  form_builder_image_picker: ^4.3.0
  auto_size_text: 3.0.0
  form_builder_phone_field: ^3.0.0
  device_info_plus: ^11.3.3
  share_plus: ^10.1.4
  hexcolor: 3.0.1
  intl: ^0.19.0
  flutter_inappwebview: ^6.1.5
  back_button_interceptor: ^8.0.4
  easy_image_viewer: ^1.5.1
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.16.0
  country_picker: ^2.0.27
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.3
  pdfrx: ^1.1.29

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: 0.9.1

flutter:
  assets:
    - lib/assets/animations/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/pdf/
  uses-material-design: true

flutter_launcher_name:
  name: Takaful Cambodia

flutter_icons:
  android: launcher_icon
  image_path: lib/assets/images/logo.jpeg
  ios: true
  remove_alpha_ios: true
